name: deploy-datacollectionrules
# This pipeline deploys Data Collection Rules (DCR) to solum managed subscription
on:
  push:
    branches:
      - 'main'
    paths:
          - "**"
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write
  checks: write
  repository-projects: read
  deployments: read
  actions: read

defaults:
  run:
    shell: pwsh

env:
  Subscription_ID: "4b9ec3e6-561c-4b1b-9496-7f33e46736b3" # S029-Omnia-Services-Standalone

jobs:
  Deploy-DRYRUN:
    name: Deploy DRYRUN
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'schedule' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy--DRYRUN
        id: DeployDRYRUN
        run: gh-action/myDeploy.ps1 -dryrun
        
  Deploy-PROD:
    name: "Deploy to PROD???"
    runs-on: ubuntu-latest
    needs: Deploy-DRYRUN
    environment: dummyEnv

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy Data Collection Rules PROD
        id: DeployPROD
        run: gh-action/myDeploy.ps1 

  Deploy-PROD-Scheduled:
    name: "Deploy to PROD on a schedule"
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy Data Collection Rules PROD
        id: DeployPROD
        run: gh-action/myDeploy.ps1 

